version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    #command: ["node", "index.js"]
    #environment:
      #- MONGODB_URI=mongodb://root:root@db:27017/todos&authSource=todos&w=1
    #volumes:
    #  - .:/app
    ports:
      - 80:4000
    depends_on:
      - db
  db:
    image: mongo:4
    restart: always
    #environment:
    #  MONGO_INITDB_ROOT_USERNAME: root
    #  MONGO_INITDB_ROOT_PASSWORD: root
